name: my_package_desktop
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  my_package:
    path: ../my_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: my_package
    platforms:
      macos:
        dartPluginClass: MyPackageDesktop
      windows:
        dartPluginClass: MyPackageDesktop
      linux:
        dartPluginClass: MyPackageDesktop
